id: I2494F9B7
ocr_import_info:
  timestamp: '2023-09-27T08:52:31.706222+00:00'
  batch_id: batch-3cab
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 09:56:16.828213+00:00
last_modified: 2023-09-27 09:56:16.828220+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM573
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM573
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པ་མཛོད་ཀྱི་དགོངས་འགྲེལ་གྱི་བསྟན་བཅོས་ཐུབ་བསྟན་ནོར་བུའི་གཏེར་མཛོད།
  languages:
  - bo
  author: འཇམ་དབྱངས་བཞད་པ ༠༡་ངག་དབང་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.9375124935578425
  ocr_word_median_confidence_index: 0.9881331
bases:
  I1NLM573_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM573_001
      total_pages: 898
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM573_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9881331
      ocr_word_mean_confidence_index: 0.9375124935578425
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
